name: Build Talos Linux for Rockchip Boards

on:
  push:
    branches:
      - main
      - development
  schedule:
    - cron: '0 3 * * 1'  # Wöchentlicher Build jeden Montag um 03:00 UTC

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Branch-Name extrahieren
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Matrix filtern
        id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@v2.0.1
        with:
          filter: '[?runOnBranch==`${{ env.branch_name }}` || runOnBranch==`any`]'
          inputFile: '.github/workflows/matrix_includes.json'

  build:
    needs: matrix_prep
    strategy:
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Build-Umgebung einrichten
        run: |
          sudo apt-get update
          sudo apt-get install -y git make gcc g++ \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          libssl-dev bc bison flex

      - name: Radxa Kernel klonen
        run: |
          git clone https://github.com/radxa/kernel.git -b ${{ matrix.kernel_branch }} kernel

      - name: Board-spezifische Konfiguration anwenden
        run: |
          cd kernel
          cp ../boards/${{ matrix.board }}.config .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: U-Boot bauen
        run: |
          git clone https://github.com/radxa/u-boot.git -b ${{ matrix.uboot_branch }} u-boot-radxa
          cd u-boot-radxa
          make ${{ matrix.board }}_defconfig
          if [ "${{ matrix.nvme }}" == "enabled" ]; then
            echo "NVMe-Unterstützung in U-Boot aktivieren..."
            # Fügen Sie hier ggf. Konfigurationen für NVMe-Unterstützung hinzu
          else
            echo "NVMe-Unterstützung ist in diesem Build deaktiviert."
          fi
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          cp idbloader.img u-boot.itb trust.img ../output/

      - name: Zusätzliche Treiber aktivieren
        run: |
          cd kernel
          echo "CONFIG_DRM_PANFROST=y" >> .config  # Panfrost GPU
          echo "CONFIG_MALI_GPU_PARTIAL_RENDER=y" >> .config
          echo "CONFIG_RTL8852BE=y" >> .config  # Netzwerk
          echo "CONFIG_RTL88XXAU=y" >> .config
          echo "CONFIG_USB_NET_CDCETHER=y" >> .config
          echo "CONFIG_USB_NET_RNDIS_HOST=y" >> .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Talos-Image bauen
        run: |
          git clone https://github.com/siderolabs/talos.git
          cd talos
          cp ../kernel/arch/arm64/boot/Image build/kernel/
          make image

      - name: Prüfsumme generieren
        run: |
          sha256sum talos/output/talos-${{ matrix.board }}.img > talos/output/talos-${{ matrix.board }}.img.sha256

      - name: Image als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: talos-${{ matrix.board }}-nvme-${{ matrix.nvme }}
          path: |
            talos/output/talos-${{ matrix.board }}.img
            talos/output/talos-${{ matrix.board }}.img.sha256
            output/idbloader.img
            output/u-boot.itb
            output/trust.img

      - name: Image veröffentlichen
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            talos/output/talos-${{ matrix.board }}.img
            talos/output/talos-${{
