name: Build Talos Linux for Rockchip Boards

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1'  # Weekly build every Monday at 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [rock5-itx, rock5b]  # List of supported boards
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git make gcc aarch64-linux-gnu-gcc libssl-dev bc bison flex

      - name: Clone Rockchip Kernel
        run: |
          git clone https://github.com/rockchip-linux/kernel.git -b stable-5.10 kernel
          cd kernel
          git clone https://github.com/google/gasket-driver.git
          cp -r gasket-driver/* drivers/staging/gasket/

      - name: Apply Board-Specific Config
        run: |
          cd kernel
          cp ../boards/${{ matrix.board }}.config .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Build U-Boot
        run: |
          git clone https://github.com/rockchip-linux/u-boot.git -b stable-2023.07 u-boot-rockchip
          cd u-boot-rockchip
          make ${{ matrix.board }}-rk3588_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          cp idbloader.img u-boot.itb trust.img ../output/

      - name: Enable Additional Drivers
        run: |
          cd kernel
          echo "CONFIG_DRM_PANFROST=y" >> .config  # Panfrost GPU
          echo "CONFIG_MALI_GPU_PARTIAL_RENDER=y" >> .config
          echo "CONFIG_RTL8852BE=y" >> .config  # Networking
          echo "CONFIG_RTL88XXAU=y" >> .config
          echo "CONFIG_USB_NET_CDCETHER=y" >> .config
          echo "CONFIG_USB_NET_RNDIS_HOST=y" >> .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Build Talos Image
        run: |
          git clone https://github.com/siderolabs/talos.git
          cd talos
          cp ../kernel/arch/arm64/boot/Image build/kernel/
          make image

      - name: Generate Checksum
        run: |
          sha256sum talos/output/talos-${{ matrix.board }}.img > talos/output/talos-${{ matrix.board }}.img.sha256

      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: talos-${{ matrix.board }}
          path: |
            talos/output/talos-${{ matrix.board }}.img
            talos/output/talos-${{ matrix.board }}.img.sha256
            output/idbloader-${{ matrix.board }}.img
            output/u-boot-${{ matrix.board }}.itb
            output/trust-${{ matrix.board }}.img

      - name: Release Image
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            talos/output/talos-${{ matrix.board }}.img
            talos/output/talos-${{ matrix.board }}.img.sha256
            output/idbloader-${{ matrix.board }}.img
            output/u-boot-${{ matrix.board }}.itb
            output/trust-${{ matrix.board }}.img
          tag_name: v${{ github.run_number }}
          body: "Talos Linux Build #${{ github.run_number }} for ${{ matrix.board }} with U-Boot modifications, GPU, and Networking support."
